#ifndef B_CAS_CARD_ERROR_CODE_H
#define B_CAS_CARD_ERROR_CODE_H

#define B_CAS_CARD_ERROR_INVALID_PARAMETER              -1
#define B_CAS_CARD_ERROR_NOT_INITIALIZED                -2
#define B_CAS_CARD_ERROR_NO_SMART_CARD_READER           -3
#define B_CAS_CARD_ERROR_ALL_READERS_CONNECTION_FAILED  -4
#define B_CAS_CARD_ERROR_NO_ENOUGH_MEMORY               -5
#define B_CAS_CARD_ERROR_TRANSMIT_FAILED                -6

#endif /* B_CAS_CARD_ERROR_CODE_H */
