#ifndef MULTI2_ERROR_CODE_H
#define MULTI2_ERROR_CODE_H

#define MULTI2_ERROR_INVALID_PARAMETER       -1
#define MULTI2_ERROR_UNSET_SYSTEM_KEY        -2
#define MULTI2_ERROR_UNSET_CBC_INIT          -3
#define MULTI2_ERROR_UNSET_SCRAMBLE_KEY      -4

#endif /* MULTI2_ERROR_CODE_H */
