#ifndef TS_SECTION_PARSER_ERROR_CODE_H
#define TS_SECTION_PARESR_ERROR_CODE_H

#define TS_SECTION_PARSER_ERROR_INVALID_PARAM        -1
#define TS_SECTION_PARSER_ERROR_NO_ENOUGH_MEMORY     -2
#define TS_SECTION_PARSER_ERROR_INVALID_TS_PID       -3
#define TS_SECTION_PARSER_ERROR_NO_SECTION_DATA      -4

#define TS_SECTION_PARSER_WARN_CRC_MISSMATCH          1
#define TS_SECTION_PARSER_WARN_LENGTH_MISSMATCH       2

#endif /* TS_SECTION_PARSER_ERROR_CODE_H */
